version: '2'
services:
  frontend:
    command: npm start
    build: traincommander_webclient/.
    volumes:
     - ./traincommander_webclient/:/frontend
    ports:
      - "8000:8000"
  backend:
    build: traincommander_api/.
    command: puma -e production
    volumes:
      - ./traincommander_api/:/backend
    ports:
      - "3000:3000"