version: '2'
services:

  frontend:
    command: npm start
    build: traincommander_webclient/.
    ports:
      - "8000:8000"
    volumes_from:
      - node_modules

  backend:
    build: traincommander_api/.
    command: puma -e production
    volumes:
      - ./traincommander_api/:/backend
    ports:
      - "3000:3000"
    volumes_from:
      - bundle

  bundle:
    image: traincommander_backend
    volumes:
      - /bundle

  node_modules:
    image: traincommander_frontend
    volumes:
      - /node_modules